name: hr_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  flutter_clean_architecture:
  dio: ^5.0.0
  internet_connection_checker:
  audioplayers:
  geolocator: ^9.0.2
  permission_handler:
  fluttertoast:
  dartz:
  equatable:
  shared_preferences:
  get_it:
  pretty_dio_logger:
  #    firebase_messaging:
  provider:
  connectivity:
  flutter_styled_toast:
  flutter_animated_dialog:
  flutter_advanced_calendar:
  url_launcher:
  flutter_svg:
  upgrader:
  flutter_lints:
  url_strategy:
  flutter_native_splash:
  cupertino_icons: ^1.0.2
  flutter_form_builder:
  syncfusion_flutter_calendar: ^20.4.49
  cached_network_image:
  loading_animation_widget:
  simple_gesture_detector:
  flutter_animate: ^4.0.0
  platform: ^3.1.0
  flutter_staggered_animations:
  percent_indicator: ^4.2.2
  go_router: ^6.0.3
  pin_code_fields: ^7.4.0
  app_settings: ^5.1.1
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  external_path: ^1.0.3
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_spinkit: ^5.2.0
  file_picker: ^5.5.0
  flutter_widget_from_html: ^0.10.5+3
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_native_splash:
  image: ""
  color: "ffffff"
  fill: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon.png"

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/language/
    - assets/audio/


  fonts:
    - family: URWDINArabic
      fonts:
        - asset: assets/fonts/URWDINArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/URWDINArabic-Bold.ttf
          weight: 800
        - asset: assets/fonts/URWDINArabic-Demi.ttf
          weight: 700
        - asset: assets/fonts/URWDINArabic-Medium.ttf
          weight: 600
        - asset: assets/fonts/URWDINArabic-Regular.ttf
          weight: 500
        - asset: assets/fonts/URWDINArabic-Light.ttf
          weight: 400