// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJbdbBTz-YFHk1FJLva_Cfbxm5bK2XhI',
    appId: '1:914659102520:web:e9d3be6645dfc00e133bcd',
    messagingSenderId: '914659102520',
    projectId: 'yousrr-f917c',
    authDomain: 'yousrr-f917c.firebaseapp.com',
    storageBucket: 'yousrr-f917c.appspot.com',
    measurementId: 'G-YJM2ETN092',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5IaYlpXdOdJLqwu3EH3Rl3kIZ0sHtpE',
    appId: '1:914659102520:android:624f1ea199d575d7133bcd',
    messagingSenderId: '914659102520',
    projectId: 'yousrr-f917c',
    storageBucket: 'yousrr-f917c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxohYScWVDVWiAczgD2Sjy6emq5lakQXQ',
    appId: '1:914659102520:ios:ea9e00aadbda6151133bcd',
    messagingSenderId: '914659102520',
    projectId: 'yousrr-f917c',
    storageBucket: 'yousrr-f917c.appspot.com',
    iosBundleId: 'com.softwareYusrPlus.yusrPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxohYScWVDVWiAczgD2Sjy6emq5lakQXQ',
    appId: '1:914659102520:ios:98f6ff14540ca825133bcd',
    messagingSenderId: '914659102520',
    projectId: 'yousrr-f917c',
    storageBucket: 'yousrr-f917c.appspot.com',
    iosBundleId: 'com.example.hrProject',
  );
}
